main_title:  "The Gently Mad"
description: "The Gently Mad is a journal of life, faith and the business of the web."
auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]