port: 4000
auto: true
main_title:  "The Gently Mad"
description: "The Gently Mad is a journal of life, faith and the business of the web."
production_url: thegentlymad.com
markdown: rdiscount
permalink: /:year/:month/:day/:title
pygments: true
rdiscount extensions: [smart]